[package]
authors = ["Daniel KJ"]
edition = "2021"
name = "debounce"
version = "0.1.0"

[dependencies]
embedded-hal = {version = "0.2.6", features = ["unproven"] }

[dev-dependencies]
failure = { version = "0.1.6", default-features = false, features = ["derive"] }